version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=notification_user
      - POSTGRES_PASSWORD=notification_password
      - POSTGRES_DB=notification_db

  redis:
    build:
      context: .
      dockerfile: compose/redis/Dockerfile
    ports:
      - 6378:6379

volumes:
  postgres_data:
